### ISSUE TITLE
Reasearch Image storage 

### ISSUE THREAD

**Issue by Winkler102** [marisela-gutierrez/petcation-station#11]
- Find a image storage solution
- Learn how to operate solution
- Teach group how to operate the technology
- Connect to Project

**Comment by virginia-rabello** [comment]
[basic setup.txt](https://github.com/marisela-gutierrez/petcation-station/files/6716387/basic.setup.txt)

Hello guys this is he basic setup to include the picture uploader in our project, I'm now working on find a way to save the picture UUID in our database.

![uploader](https://user-images.githubusercontent.com/79593818/123431019-d0cf7680-d596-11eb-9798-a7a29f837731.png)

And this is how it looks like!

**Comment by virginia-rabello** [comment]
The picture uploader was succesfully incorporated in the main user profile.
