### ISSUE TITLE
Full Pet Profile Partial 

### ISSUE THREAD

**Issue by Winkler102** [marisela-gutierrez/petcation-station#26]
Create a partial to display a card of pet
Includes pet information: 
- Name
- Age
- Species
- Breed
- Gender
- Interact with other animals
- Behavior
- Spade-neutered okay
- Bio
- Feeding habits
- Potty trained
- Picture

**Comment by Winkler102** [comment]
add info from pet owner.

**Comment by marisela-gutierrez** [comment]
full pet profile
